import traceback
raise Exception("hello world")

print(traceb)